// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MSP.Client {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("StartMediaViewController")]
	public partial class StartMediaViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_titleTxt;
		
		private MonoTouch.UIKit.UIButton __mt_localBtn;
		
		private MonoTouch.UIKit.UIButton __mt_globalBtn;
		
		private MonoTouch.UIKit.UIButton __mt_mapBtn;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("GoToMap:")]
		partial void GoToMap (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("titleTxt")]
		private MonoTouch.UIKit.UILabel titleTxt {
			get {
				this.__mt_titleTxt = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("titleTxt")));
				return this.__mt_titleTxt;
			}
			set {
				this.__mt_titleTxt = value;
				this.SetNativeField("titleTxt", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("localBtn")]
		private MonoTouch.UIKit.UIButton localBtn {
			get {
				this.__mt_localBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("localBtn")));
				return this.__mt_localBtn;
			}
			set {
				this.__mt_localBtn = value;
				this.SetNativeField("localBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("globalBtn")]
		private MonoTouch.UIKit.UIButton globalBtn {
			get {
				this.__mt_globalBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("globalBtn")));
				return this.__mt_globalBtn;
			}
			set {
				this.__mt_globalBtn = value;
				this.SetNativeField("globalBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("mapBtn")]
		private MonoTouch.UIKit.UIButton mapBtn {
			get {
				this.__mt_mapBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("mapBtn")));
				return this.__mt_mapBtn;
			}
			set {
				this.__mt_mapBtn = value;
				this.SetNativeField("mapBtn", value);
			}
		}
	}
}
