// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MSP.Client {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("StartMapViewController")]
	public partial class StartMapViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.MapKit.MKMapView __mt_mapView;
		
		private MonoTouch.UIKit.UIButton __mt_backBtn;
		
		private MonoTouch.UIKit.UILabel __mt_titleTxt;
		
		private MonoTouch.UIKit.UILabel __mt_worldTxt;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("mapView")]
		private MonoTouch.MapKit.MKMapView mapView {
			get {
				this.__mt_mapView = ((MonoTouch.MapKit.MKMapView)(this.GetNativeField("mapView")));
				return this.__mt_mapView;
			}
			set {
				this.__mt_mapView = value;
				this.SetNativeField("mapView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("backBtn")]
		private MonoTouch.UIKit.UIButton backBtn {
			get {
				this.__mt_backBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("backBtn")));
				return this.__mt_backBtn;
			}
			set {
				this.__mt_backBtn = value;
				this.SetNativeField("backBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("titleTxt")]
		private MonoTouch.UIKit.UILabel titleTxt {
			get {
				this.__mt_titleTxt = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("titleTxt")));
				return this.__mt_titleTxt;
			}
			set {
				this.__mt_titleTxt = value;
				this.SetNativeField("titleTxt", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("worldTxt")]
		private MonoTouch.UIKit.UILabel worldTxt {
			get {
				this.__mt_worldTxt = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("worldTxt")));
				return this.__mt_worldTxt;
			}
			set {
				this.__mt_worldTxt = value;
				this.SetNativeField("worldTxt", value);
			}
		}
	}
}
