// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MSP.Client {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("LoginPageGarde")]
	public partial class LoginPageGarde {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_loginBtn;
		
		private MonoTouch.UIKit.UIButton __mt_registerBtn;
		
		private MonoTouch.UIKit.UIButton __mt_facebookBtn;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("loginBtn")]
		private MonoTouch.UIKit.UIButton loginBtn {
			get {
				this.__mt_loginBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("loginBtn")));
				return this.__mt_loginBtn;
			}
			set {
				this.__mt_loginBtn = value;
				this.SetNativeField("loginBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("registerBtn")]
		private MonoTouch.UIKit.UIButton registerBtn {
			get {
				this.__mt_registerBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("registerBtn")));
				return this.__mt_registerBtn;
			}
			set {
				this.__mt_registerBtn = value;
				this.SetNativeField("registerBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("facebookBtn")]
		private MonoTouch.UIKit.UIButton facebookBtn {
			get {
				this.__mt_facebookBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("facebookBtn")));
				return this.__mt_facebookBtn;
			}
			set {
				this.__mt_facebookBtn = value;
				this.SetNativeField("facebookBtn", value);
			}
		}
	}
}
