// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MSP.Client {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("SearchViewController")]
	public partial class SearchViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_backBtn;
		
		private MonoTouch.UIKit.UIButton __mt_keywordsBtn;
		
		private MonoTouch.UIKit.UIButton __mt_usersBtn;
		
		private MonoTouch.UIKit.UIButton __mt_mapBtn;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("backBtn")]
		private MonoTouch.UIKit.UIButton backBtn {
			get {
				this.__mt_backBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("backBtn")));
				return this.__mt_backBtn;
			}
			set {
				this.__mt_backBtn = value;
				this.SetNativeField("backBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("keywordsBtn")]
		private MonoTouch.UIKit.UIButton keywordsBtn {
			get {
				this.__mt_keywordsBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("keywordsBtn")));
				return this.__mt_keywordsBtn;
			}
			set {
				this.__mt_keywordsBtn = value;
				this.SetNativeField("keywordsBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("usersBtn")]
		private MonoTouch.UIKit.UIButton usersBtn {
			get {
				this.__mt_usersBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("usersBtn")));
				return this.__mt_usersBtn;
			}
			set {
				this.__mt_usersBtn = value;
				this.SetNativeField("usersBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("mapBtn")]
		private MonoTouch.UIKit.UIButton mapBtn {
			get {
				this.__mt_mapBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("mapBtn")));
				return this.__mt_mapBtn;
			}
			set {
				this.__mt_mapBtn = value;
				this.SetNativeField("mapBtn", value);
			}
		}
	}
}
