// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MSP.Client {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("SocialNetworksShareViewController")]
	public partial class SocialNetworksShareViewController {
		
		private MonoTouch.UIKit.UIButton __mt_backBtn;
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_facebookBtn;
		
		private MonoTouch.UIKit.UIButton __mt_twitterBtn;
		
		private MonoTouch.UIKit.UILabel __mt_selfshareLbl;
		
		private MonoTouch.UIKit.UIButton __mt_selfshareBtn;
		
		private MonoTouch.UIKit.UILabel __mt_selfShareSubLbl;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("backBtn")]
		private MonoTouch.UIKit.UIButton backBtn {
			get {
				this.__mt_backBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("backBtn")));
				return this.__mt_backBtn;
			}
			set {
				this.__mt_backBtn = value;
				this.SetNativeField("backBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("facebookBtn")]
		private MonoTouch.UIKit.UIButton facebookBtn {
			get {
				this.__mt_facebookBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("facebookBtn")));
				return this.__mt_facebookBtn;
			}
			set {
				this.__mt_facebookBtn = value;
				this.SetNativeField("facebookBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("twitterBtn")]
		private MonoTouch.UIKit.UIButton twitterBtn {
			get {
				this.__mt_twitterBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("twitterBtn")));
				return this.__mt_twitterBtn;
			}
			set {
				this.__mt_twitterBtn = value;
				this.SetNativeField("twitterBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("selfshareLbl")]
		private MonoTouch.UIKit.UILabel selfshareLbl {
			get {
				this.__mt_selfshareLbl = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("selfshareLbl")));
				return this.__mt_selfshareLbl;
			}
			set {
				this.__mt_selfshareLbl = value;
				this.SetNativeField("selfshareLbl", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("selfshareBtn")]
		private MonoTouch.UIKit.UIButton selfshareBtn {
			get {
				this.__mt_selfshareBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("selfshareBtn")));
				return this.__mt_selfshareBtn;
			}
			set {
				this.__mt_selfshareBtn = value;
				this.SetNativeField("selfshareBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("selfShareSubLbl")]
		private MonoTouch.UIKit.UILabel selfShareSubLbl {
			get {
				this.__mt_selfShareSubLbl = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("selfShareSubLbl")));
				return this.__mt_selfShareSubLbl;
			}
			set {
				this.__mt_selfShareSubLbl = value;
				this.SetNativeField("selfShareSubLbl", value);
			}
		}
	}
}
